// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyA_I_XpeEd542zSvmqBBnslnPxYFKoOL48',
//     appId: '1:687529134060:web:741a0ffa0c6f3a533922c9',
//     messagingSenderId: '687529134060',
//     projectId: 'bhartiyaseller-10ba5',
//     authDomain: 'bhartiyaseller-10ba5.firebaseapp.com',
//     storageBucket: 'bhartiyaseller-10ba5.appspot.com',
//     measurementId: 'G-KRK17V6XDJ',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyD4gcveyf5NwPMxJluWQwzvUZfaT8GGwU0',
//     appId: '1:687529134060:android:27b3c05e47a5234b3922c9',
//     messagingSenderId: '687529134060',
//     projectId: 'bhartiyaseller-10ba5',
//     storageBucket: 'bhartiyaseller-10ba5.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBbaCqWQUfIZYcFSNgVvq1PrjlvVILYw1E',
//     appId: '1:687529134060:ios:8e7de1dd0dd8c8083922c9',
//     messagingSenderId: '687529134060',
//     projectId: 'bhartiyaseller-10ba5',
//     storageBucket: 'bhartiyaseller-10ba5.appspot.com',
//     androidClientId: '687529134060-a5ro413ovmb7hn0jum2u85fb1lljr83s.apps.googleusercontent.com',
//     iosClientId: '687529134060-idrak8v5mpv8f104u751m0nr311i3qqj.apps.googleusercontent.com',
//     iosBundleId: 'com.example.bhkSellerApp',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBbaCqWQUfIZYcFSNgVvq1PrjlvVILYw1E',
//     appId: '1:687529134060:ios:8e7de1dd0dd8c8083922c9',
//     messagingSenderId: '687529134060',
//     projectId: 'bhartiyaseller-10ba5',
//     storageBucket: 'bhartiyaseller-10ba5.appspot.com',
//     androidClientId: '687529134060-a5ro413ovmb7hn0jum2u85fb1lljr83s.apps.googleusercontent.com',
//     iosClientId: '687529134060-idrak8v5mpv8f104u751m0nr311i3qqj.apps.googleusercontent.com',
//     iosBundleId: 'com.example.bhkSellerApp',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyA_I_XpeEd542zSvmqBBnslnPxYFKoOL48',
//     appId: '1:687529134060:web:1c63173def9e2c5d3922c9',
//     messagingSenderId: '687529134060',
//     projectId: 'bhartiyaseller-10ba5',
//     authDomain: 'bhartiyaseller-10ba5.firebaseapp.com',
//     storageBucket: 'bhartiyaseller-10ba5.appspot.com',
//     measurementId: 'G-FFDG462Y5Q',
//   );
//
// }